Repository SG-LEMONADE/CREAM, pull requests merged in 2022-02, with the labels that each got.

#52 feat(shop): SHOP 화면 구성.
  src/client/next.config.js
  src/client/package.json
  src/client/src/components/atoms/BannerImage/index.tsx
  src/client/src/components/atoms/Checkbox/index.tsx
  src/client/src/components/atoms/Icon/index.stories.tsx
  src/client/src/components/atoms/Icon/index.tsx
  src/client/src/components/atoms/Icon/svg/index.ts
  src/client/src/components/atoms/Icon/svg/turnOn.svg
  src/client/src/components/atoms/PriceThumbnail/index.tsx
  src/client/src/components/atoms/ProductImage/index.tsx
  src/client/src/components/atoms/ProductName/index.tsx
  src/client/src/components/atoms/TagItem/index.stories.tsx
  src/client/src/components/atoms/TagItem/index.tsx
  src/client/src/components/molecules/Modal/index.tsx
  src/client/src/components/molecules/ProductInfo/index.tsx
  src/client/src/components/molecules/ProductSizeSelectGrid/index.tsx
  src/client/src/components/molecules/ProductSmallInfo/index.tsx
  src/client/src/components/molecules/QuickFilterBar/index.stories.tsx
  src/client/src/components/molecules/QuickFilterBar/index.tsx
  src/client/src/components/molecules/SearchFilterItem/index.tsx
  src/client/src/components/organisms/Dropdown/index.stories.tsx
  src/client/src/components/organisms/Dropdown/index.tsx
  src/client/src/components/organisms/Footer/index.tsx
  src/client/src/components/organisms/HeaderTop/index.tsx
  src/client/src/components/organisms/JoinForm/index.tsx
  src/client/src/components/organisms/LoginForm/index.tsx
  src/client/src/components/organisms/ProductThumbnail/index.stories.tsx
  src/client/src/components/organisms/ProductThumbnail/index.tsx
  src/client/src/components/organisms/SearchFilterBar/index.stories.tsx
  src/client/src/components/organisms/SearchFilterBar/index.tsx
  src/client/src/components/organisms/ShopTopBox/index.stories.tsx
  src/client/src/components/organisms/ShopTopBox/index.tsx
  src/client/src/components/organisms/Slider/index.tsx
  src/client/src/components/templates/HomeTemplate/index.tsx
  src/client/src/components/templates/NavTemplate/index.stories.tsx
  src/client/src/components/templates/NavTemplate/index.tsx
  src/client/src/components/templates/ShopTemplate/index.stories.tsx
  src/client/src/components/templates/ShopTemplate/index.tsx
  src/client/src/lib/customAxios.ts
  src/client/src/lib/fetcher.ts
  src/client/src/pages/index.tsx
  src/client/src/pages/join.tsx
  src/client/src/pages/login.tsx
  src/client/src/pages/search.tsx
  src/client/src/types/index.ts
  src/client/src/utils/filterId.ts
  src/client/src/utils/query.ts
  src/client/src/utils/user.ts
  src/client/yarn.lock
Labels: 🚀 enhancement

#53 feat(template): home template 작성.
  src/client/src/components/atoms/BannerImage/index.tsx
  src/client/src/components/atoms/ShortcutItem/index.tsx
  src/client/src/components/molecules/Shortcuts/index.tsx
  src/client/src/components/templates/HomeTemplate/index.stories.tsx
  src/client/src/components/templates/HomeTemplate/index.tsx
  src/client/src/pages/index.tsx
Labels: 🚀 enhancement

#54 feat(homeProduct): 홈 product 컴포넌트 organism 작성.
  src/client/next.config.js
  src/client/src/components/molecules/ProductInfo/index.tsx
  src/client/src/components/organisms/HomeProduct/index.stories.tsx
  src/client/src/components/organisms/HomeProduct/index.tsx
  src/client/src/components/organisms/ProductThumbnail/index.stories.tsx
  src/client/src/components/organisms/ProductThumbnail/index.tsx
  src/client/src/components/templates/ShopTemplate/index.tsx
  src/client/src/types/index.ts
Labels: 🚀 enhancement

#55 feat(home): 홈 컴포넌트 작성. (#1205)
  src/client/next.config.js
  src/client/package.json
  src/client/src/components/atoms/BannerImage/index.tsx
  src/client/src/components/atoms/HeaderMainItem/index.tsx
  src/client/src/components/atoms/ShortcutItem/index.tsx
  src/client/src/components/molecules/ProductThumbnailImage/index.tsx
  src/client/src/components/molecules/SearchFilterItem/index.tsx
  src/client/src/components/organisms/Dropdown/index.tsx
  src/client/src/components/organisms/HeaderMain/index.tsx
  src/client/src/components/organisms/HomeProduct/index.stories.tsx
  src/client/src/components/organisms/HomeProduct/index.tsx
  src/client/src/components/organisms/ProductThumbnail/index.tsx
  src/client/src/components/organisms/SearchFilterBar/index.tsx
  src/client/src/components/templates/HomeTemplate/index.tsx
  src/client/src/components/templates/ShopTemplate/index.tsx
  src/client/src/lib/fetcher.ts
  src/client/src/pages/index.tsx
  src/client/src/pages/search.tsx
  src/client/src/types/index.ts
  src/client/src/utils/query.ts
  src/client/yarn.lock
Labels: 🚀 enhancement

#56 feat(search): 검색 모달 작성.
  src/client/src/components/atoms/Input/index.tsx
  src/client/src/components/molecules/Modal/index.stories.tsx
  src/client/src/components/molecules/Modal/index.tsx
  src/client/src/components/organisms/HeaderMain/index.tsx
  src/client/src/components/templates/NavTemplate/index.stories.tsx
Labels: 🚀 enhancement

#58 feat(mypage): 마이페이지 컴포넌트 작성. (#1225)
  src/client/src/components/atoms/MyPageSidebarItem/index.tsx
  src/client/src/components/molecules/TradeHistoryItem/index.tsx
  src/client/src/components/organisms/HeaderTop/index.tsx
  src/client/src/components/organisms/MyPageSidebar/index.tsx
  src/client/src/components/organisms/TradeHistory/index.tsx
  src/client/src/components/templates/MyPageTemplate/index.stories.tsx
  src/client/src/components/templates/MyPageTemplate/index.tsx
  src/client/src/lib/fetcher.ts
  src/client/src/pages/my.tsx
  src/client/src/pages/products/[id].tsx
  src/client/src/types/index.ts
Labels: 🚀 enhancement

#60 feat(trade): 구매, 판매 내역 구현 (#1226)
  src/client/src/components/atoms/MyPageSidebarItem/index.tsx
  src/client/src/components/molecules/ProductSmallInfo/index.tsx
  src/client/src/components/molecules/TradeHistoryItem/index.tsx
  src/client/src/components/molecules/TradeTab/index.stories.tsx
  src/client/src/components/molecules/TradeTab/index.tsx
  src/client/src/components/organisms/MyPageSidebar/index.tsx
  src/client/src/components/organisms/ProductGrid/index.stories.tsx
  src/client/src/components/organisms/ProductGrid/index.tsx
  src/client/src/components/organisms/TradeDetail/index.stories.tsx
  src/client/src/components/organisms/TradeDetail/index.tsx
  src/client/src/components/organisms/TradeHistory/index.stories.tsx
  src/client/src/components/templates/MyPageTemplate/index.tsx
  src/client/src/pages/my/buying.tsx
  src/client/src/pages/my/index.tsx
  src/client/src/pages/my/selling.tsx
  src/client/src/types/index.ts
Labels: 🚀 enhancement

#61 feat(wish): 마이페이지 찜 목록 컴포넌트 작성.
  src/client/src/components/atoms/Knob/index.tsx
  src/client/src/components/molecules/ProductSmallInfo/index.tsx
  src/client/src/components/organisms/MyPageSidebar/index.tsx
  src/client/src/components/organisms/ProductWish/index.stories.tsx
  src/client/src/components/organisms/ProductWish/index.tsx
  src/client/src/pages/my/wish.tsx
Labels: 🚀 enhancement

#64 feat(profile): 개인정보 수정 기능 구현. (#1228)
  src/client/package.json
  src/client/src/components/atoms/Input/index.tsx
  src/client/src/components/molecules/Modal/index.tsx
  src/client/src/components/molecules/UserDetail/index.stories.tsx
  src/client/src/components/molecules/UserDetail/index.tsx
  src/client/src/components/organisms/Floater/index.tsx
  src/client/src/components/organisms/HeaderTop/index.tsx
  src/client/src/components/organisms/LoginForm/index.tsx
  src/client/src/components/organisms/ProductGrid/index.tsx
  src/client/src/components/organisms/ProductThumbnail/index.tsx
  src/client/src/components/organisms/ProductWish/index.tsx
  src/client/src/components/organisms/ProfileEdit/index.stories.tsx
  src/client/src/components/organisms/ProfileEdit/index.tsx
  src/client/src/components/organisms/TradeDetail/index.tsx
  src/client/src/components/organisms/TradeHistory/index.tsx
  src/client/src/components/organisms/UserMembership/index.tsx
  src/client/src/context/user.ts
  src/client/src/pages/_app.tsx
  src/client/src/pages/my/buying.tsx
  src/client/src/pages/my/index.tsx
  src/client/src/pages/my/profile.tsx
  src/client/src/pages/my/wish.tsx
  src/client/src/provider/UserProvider.tsx
  src/client/src/types/index.ts
  src/client/src/utils/patch.ts
  src/client/yarn.lock
Labels: 🚀 enhancement

#65 feat(transaction): 구매 및 판매 버튼 클릭시 사이즈 선택하는 화면 개발.
  src/client/src/components/atoms/Button/index.tsx
  src/client/src/components/atoms/ProductSizeSelect/index.tsx
  src/client/src/components/atoms/TransactionTitle/index.stories.tsx
  src/client/src/components/atoms/TransactionTitle/index.tsx
  src/client/src/components/molecules/ProductSizeSelectGrid/index.stories.tsx
  src/client/src/components/molecules/ProductSizeSelectGrid/index.tsx
  src/client/src/components/molecules/ProductSmallInfo/index.stories.tsx
  src/client/src/components/molecules/ProductSmallInfo/index.tsx
  src/client/src/components/templates/ProductTemplate/index.tsx
  src/client/src/components/templates/SizeSelectTemplate/index.stories.tsx
  src/client/src/components/templates/SizeSelectTemplate/index.tsx
  src/client/src/pages/buy/[id].tsx
  src/client/src/pages/buy/select/[id].tsx
  src/client/src/pages/sell/[id].tsx
  src/client/src/pages/sell/select/[id].tsx
Labels: 🚀 enhancement

#67 docs: client 리드미 작성.
  docs/code_document_client.md
  src/client/src/components/organisms/ProfileEdit/index.tsx
Labels: 📝 documentation

#68 docs: server doc 및 주석 추가
  docs/code_document_server.md
  src/server/gateway/src/main/kotlin/com/cream/gateway/filter/JwtAuthFilter.kt
  src/server/product/src/main/kotlin/com/cream/product/persistence/ProductRepository.kt
  src/server/product/src/main/kotlin/com/cream/product/persistence/TradeRepository.kt
  src/server/user/src/main/kotlin/com/cream/user/controller/UserController.kt
  src/server/user/src/main/kotlin/com/cream/user/service/UserService.kt
  src/server/user/src/main/kotlin/com/cream/user/utils/UserMailSender.kt
Labels: 📝 documentation

#76 feat(trade): 거래 페이지 작성 및 api 연결. (#1255)
  src/client/src/components/atoms/Button/index.tsx
  src/client/src/components/atoms/Input/index.tsx
  src/client/src/components/atoms/Knob/index.tsx
  src/client/src/components/molecules/DeadLine/index.stories.tsx
  src/client/src/components/molecules/DeadLine/index.tsx
  src/client/src/components/molecules/PriceInfo/index.stories.tsx
  src/client/src/components/molecules/PriceInfo/index.tsx
  src/client/src/components/molecules/PriceInput/index.stories.tsx
  src/client/src/components/molecules/PriceInput/index.tsx
  src/client/src/components/molecules/PriceTab/index.stories.tsx
  src/client/src/components/molecules/PriceTab/index.tsx
  src/client/src/components/molecules/ProductSizeSelectGrid/index.tsx
  src/client/src/components/molecules/ProductSmallInfo/index.tsx
  src/client/src/components/organisms/HeaderTop/index.tsx
  src/client/src/components/organisms/JoinForm/index.tsx
  src/client/src/components/organisms/LoginForm/index.tsx
  src/client/src/components/organisms/ProductThumbnail/index.tsx
  src/client/src/components/organisms/TradeDetail/index.tsx
  src/client/src/components/organisms/TradeHistory/index.tsx
  src/client/src/components/templates/ProductTemplate/index.tsx
  src/client/src/components/templates/SizeSelectTemplate/index.tsx
  src/client/src/components/templates/TransactionTemplate/index.stories.tsx
  src/client/src/components/templates/TransactionTemplate/index.tsx
  src/client/src/pages/buy/[id].tsx
  src/client/src/pages/buy/select/[id].tsx
  src/client/src/pages/my/wish.tsx
  src/client/src/pages/search.tsx
  src/client/src/pages/sell/[id].tsx
  src/client/src/pages/sell/select/[id].tsx
Labels: 🚀 enhancement

#77 feat(filter): 상품 필터링 적용(#1251)
  src/ios/Cream.xcodeproj/project.pbxproj
  src/ios/Cream/Data/Network/APIEndpoints.swift
  src/ios/Cream/Data/Repositories/ProductRepository.swift
  src/ios/Cream/Domain/Entities/Filter.swift
  src/ios/Cream/Domain/Interfaces/Repositories/ProductRepositoryInterface.swift
  src/ios/Cream/Domain/UseCases/ProductUseCase.swift
  src/ios/Cream/Extension/NotificationName+.swift
  src/ios/Cream/Presentation/Base/NavigateMenuBaseController.swift
  src/ios/Cream/Presentation/FilterScene/DetailFilterViewController.swift
  src/ios/Cream/Presentation/FilterScene/DetailFilterViewModel.swift
  src/ios/Cream/Presentation/FilterScene/FilterViewController.swift
  src/ios/Cream/Presentation/FilterScene/FilterViewModel.swift
  src/ios/Cream/Presentation/HomeScene/HomeViewController.swift
  src/ios/Cream/Presentation/ProductListScene/ProductListViewController.swift
  src/ios/Cream/Presentation/ProductListScene/ProductListViewModel.swift
  src/ios/Cream/Presentation/ProductListScene/Views/ShopViewFilterHeaderView.swift
  src/ios/Cream/Presentation/ProductScene/ProductViewModel.swift
Labels: 🚀 enhancement

#78 feat(pagination): 페이지네이션 구현. (#1268)
  src/client/package.json
  src/client/src/components/atoms/Icon/index.stories.tsx
  src/client/src/components/atoms/Icon/svg/index.ts
  src/client/src/components/atoms/Icon/svg/trash.svg
  src/client/src/components/atoms/ProductImage/index.stories.tsx
  src/client/src/components/atoms/TransactionTitle/index.stories.tsx
  src/client/src/components/atoms/TransactionTitle/index.tsx
  src/client/src/components/molecules/Dropdown/index.stories.tsx
  src/client/src/components/molecules/Dropdown/index.tsx
  src/client/src/components/molecules/ProductSmallInfo/index.stories.tsx
  src/client/src/components/molecules/SearchFilterItem/index.tsx
  src/client/src/components/organisms/ProductWish/index.tsx
  src/client/src/components/organisms/SearchFilterBar/index.tsx
  src/client/src/components/organisms/Skeletons/index.stories.tsx
  src/client/src/components/organisms/Skeletons/index.tsx
  src/client/src/components/organisms/TradeDetail/index.stories.tsx
  src/client/src/components/organisms/TradeDetail/index.tsx
  src/client/src/components/organisms/TradeHistory/index.stories.tsx
  src/client/src/components/organisms/TradeHistory/index.tsx
  src/client/src/components/templates/ShopTemplate/index.tsx
  src/client/src/pages/buy/[id].tsx
  src/client/src/pages/my/buying.tsx
  src/client/src/pages/my/selling.tsx
  src/client/src/pages/my/wish.tsx
  src/client/src/pages/search.tsx
  src/client/yarn.lock
Labels: 🚀 enhancement

#81 feat(wish): 상품 찜 기능 구현(#1269)
  src/ios/Cream/Data/Network/APIEndpoints.swift
  src/ios/Cream/Data/Repositories/ProductRepository.swift
  src/ios/Cream/Domain/Interfaces/Repositories/ProductRepositoryInterface.swift
  src/ios/Cream/Domain/UseCases/ProductUseCase.swift
  src/ios/Cream/Presentation/Base/Views/WishButton.swift
  src/ios/Cream/Presentation/ProductListScene/Views/ProductListItemCell.swift
  src/ios/Cream/Presentation/ProductScene/ProductViewController.swift
  src/ios/Cream/Presentation/ProductScene/ProductViewModel.swift
  src/ios/Cream/Presentation/SelectScene/SelectViewController.swift
  src/ios/Cream/Presentation/SelectScene/SelectViewModel.swift
  src/ios/Cream/Presentation/SelectScene/Views/WishCell.swift
Labels: 🚀 enhancement

#84 refactor: selectVC 통합에 따른 sizeSelectVC 파일 제거(#1269)
  src/ios/Cream.xcodeproj/project.pbxproj
  src/ios/Cream/Assets.xcassets/AppIcon.appiconset/1024.png
  src/ios/Cream/Assets.xcassets/AppIcon.appiconset/114.png
  src/ios/Cream/Assets.xcassets/AppIcon.appiconset/120.png
  src/ios/Cream/Assets.xcassets/AppIcon.appiconset/180.png
  src/ios/Cream/Assets.xcassets/AppIcon.appiconset/29.png
  src/ios/Cream/Assets.xcassets/AppIcon.appiconset/40.png
  src/ios/Cream/Assets.xcassets/AppIcon.appiconset/57.png
  src/ios/Cream/Assets.xcassets/AppIcon.appiconset/58.png
  src/ios/Cream/Assets.xcassets/AppIcon.appiconset/60.png
  src/ios/Cream/Assets.xcassets/AppIcon.appiconset/80.png
  src/ios/Cream/Assets.xcassets/AppIcon.appiconset/87.png
  src/ios/Cream/Assets.xcassets/AppIcon.appiconset/Contents.json
  src/ios/Cream/Presentation/Base/Views/TradeButton.swift
  src/ios/Cream/Presentation/HomeScene/Views/HomeViewItemCell.swift
  src/ios/Cream/Presentation/MyPageScene/Views/MyInfoCell.swift
  src/ios/Cream/Presentation/ProductListScene/Views/ProductListItemCell.swift
  src/ios/Cream/Presentation/ProductListScene/Views/ShopBannerCell.swift
  src/ios/Cream/Presentation/ProductScene/ProductViewController.swift
  src/ios/Cream/Presentation/SelectScene/SelectViewController.swift
  src/ios/Cream/Presentation/SizeSelectScene/SizeListView.swift
  src/ios/Cream/Presentation/SizeSelectScene/SizeListViewController.swift
  src/ios/Cream/Presentation/SizeSelectScene/SizeListViewModel.swift
  src/ios/Cream/Presentation/TradeProcessScene/ProcessViewController.swift
  src/ios/Cream/Presentation/TradeScene/TradeViewController.swift
  src/ios/Cream/SupportFile/ImageCache.swift
Labels: 🛠 refactoring

#92 env: 배포 환경 세팅
  src/client/next.config.js
  src/client/src/pages/_app.tsx
Labels: 🗻 environment

#94 feat(trade): 입찰 삭제 기능 구현 및 스와이프 이벤트 적용(#1269)
  src/ios/Cream/Data/Network/APIEndpoints.swift
  src/ios/Cream/Data/Network/DataMapping/TradeResponseDTO+Mapping.swift
  src/ios/Cream/Data/Repositories/ProductRepository.swift
  src/ios/Cream/Domain/Entities/Trade.swift
  src/ios/Cream/Domain/Interfaces/Repositories/TradeRepositoryInterface.swift
  src/ios/Cream/Domain/UseCases/MyPageUseCase.swift
  src/ios/Cream/Presentation/ManagementScene/ManagementViewController.swift
  src/ios/Cream/Presentation/ManagementScene/ManagementViewModel.swift
  src/ios/Cream/Presentation/ManagementScene/Views/ManagementCell.swift
  src/ios/Cream/Presentation/MyPageScene/MyPageView.swift
  src/ios/Cream/Presentation/MyPageScene/MyPageViewController.swift
  src/ios/Cream/Presentation/ProductListScene/ProductListViewController.swift
  src/ios/Cream/Presentation/TradeProcessScene/ProcessViewModel.swift
Labels: 🐞 bug

#96 bug: Fix bugs.
  src/client/next.config.js
  src/client/src/components/molecules/TradeHistoryItem/index.tsx
  src/client/src/components/molecules/TradeTab/index.tsx
  src/client/src/components/organisms/Graph/index.tsx
  src/client/src/components/organisms/SearchFilterBar/index.tsx
  src/client/src/components/organisms/Slider/index.tsx
  src/client/src/components/organisms/TradeDetail/index.tsx
  src/client/src/components/organisms/TradeHistory/index.tsx
  src/client/src/components/templates/HomeTemplate/index.tsx
  src/client/src/components/templates/ProductTemplate/index.tsx
  src/client/src/components/templates/SizeSelectTemplate/index.stories.tsx
  src/client/src/types/index.ts
Labels: 🚀 enhancement

#97 fix: 타입 변경에 따른 더미 데이터 파라미터 수정(#1344)
  src/ios/Cream/Presentation/SelectScene/SelectViewModel.swift
  src/ios/CreamTests/Mock/MockMyPageUseCase.swift
  src/ios/CreamTests/ViewModelUnitTest/ManagementViewModelSpec.swift
Labels: 🐞 bug
